# Generated by Django 4.2.10 on 2024-02-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_equipo_anho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.equipo')),
            ],
        ),
    ]
